spring:
  application:
    name: ms-teacher
  zipkin:
    base-url: http://localhost:9411
h2:
  console:
    enabled: true
server:
  port: 7878

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8763/eureka
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

